import type { IngestedItem } from "./catalog";

/**
 * Migration generation for ingested venues.
 *
 * The model returns JSON and this file writes the SQL. Never the other way
 * round: a model writing SQL directly can produce broken quoting that only
 * fails once it is pasted into a production SQL editor, and an apostrophe in
 * a venue name ("Auntie Efua's") is enough to do it.
 */

/** Single-quoted SQL literal with quotes doubled. Null for empty values. */
function lit(value: string | null | undefined): string {
  if (value === null || value === undefined) return "null";
  const trimmed = value.trim();
  if (!trimmed) return "null";
  return `'${trimmed.replace(/'/g, "''")}'`;
}

/** Numeric literal, or null. Rejects anything non-finite rather than emitting NaN. */
function num(value: number | null | undefined): string {
  if (value === null || value === undefined || !Number.isFinite(value)) return "null";
  return String(value);
}

function bool(value: boolean): string {
  return value ? "true" : "false";
}

/** text[] literal, e.g. array['romantic','calm']. */
function textArray(values: string[]): string {
  const clean = values.map((v) => v.trim()).filter(Boolean);
  if (!clean.length) return "'{}'";
  return `array[${clean.map((v) => lit(v)).join(", ")}]`;
}

export interface VenueSql {
  name: string;
  type: string;
  areaName: string;
  price_band: string;
  avg_cost_per_person_ghs: number;
  description: string;
  vibe_tags: string[];
  best_for: string[];
  dress_code: string | null;
  reservation_required: boolean;
  instagram_handle: string | null;
  phone: string | null;
  google_maps_url: string | null;
  image_url: string | null;
  lat: number | null;
  lng: number | null;
}

/**
 * One migration inserting a venue and its menu items atomically.
 *
 * The area is resolved by name at run time rather than baked in as a UUID, so
 * the same file works against any environment. The insert is wrapped in a
 * transaction and guards on the area existing — a missing area would otherwise
 * insert a venue with a null area_id and fail confusingly downstream.
 */
export function buildVenueMigration(venue: VenueSql, items: IngestedItem[]): string {
  const generatedAt = new Date().toISOString().slice(0, 10);

  const itemRows = items
    .map(
      (i) =>
        `    (${lit(i.name)}, ${lit(i.category)}::menu_category, ${num(i.price_ghs)}, ${lit(i.notes)})`
    )
    .join(",\n");

  // phone lands in phone_pending, never phone. An imported number has had no
  // human check, and the reservation flow dials `phone` under our own name.
  const venueColumns = `    name, type, area_id, vibe_tags, dress_code, price_band,
    avg_cost_per_person_ghs, description, best_for, reservation_required,
    instagram_handle, phone_pending, phone_status, phone_source,
    google_maps_url, image_url, lat, lng, is_active`;

  const venueValues = `    ${lit(venue.name)},
    ${lit(venue.type)}::venue_type,
    (select id from public.areas where name = ${lit(venue.areaName)}),
    ${textArray(venue.vibe_tags)},
    ${lit(venue.dress_code)},
    ${lit(venue.price_band)}::price_band,
    ${num(venue.avg_cost_per_person_ghs)},
    ${lit(venue.description)},
    ${textArray(venue.best_for)},
    ${bool(venue.reservation_required)},
    ${lit(venue.instagram_handle)},
    ${lit(venue.phone)},
    ${venue.phone ? "'pending'" : "'none'"}::phone_status,
    'admin ingest — unreviewed',
    ${lit(venue.google_maps_url)},
    ${lit(venue.image_url)},
    ${num(venue.lat)},
    ${num(venue.lng)},
    true`;

  // A data-modifying CTE must be attached to a main statement, so the
  // CTE form is only valid when there are menu rows to insert. With no items
  // it has to be a plain INSERT or the migration will not parse.
  const insertBlock = items.length
    ? `with new_venue as (
  insert into public.venues (
${venueColumns}
  ) values (
${venueValues}
  )
  returning id
)
-- Menu items. Prices are per single item, as printed on the menu.
insert into public.menu_items (venue_id, name, category, price_ghs, notes)
-- Columns are cast explicitly: a VALUES list whose every row is null for a
-- column leaves Postgres unable to infer its type, which fails at run time.
select
  (select id from new_venue),
  x.name::text,
  x.category,
  x.price_ghs::numeric,
  x.notes::text
from (values
${itemRows}
) as x(name, category, price_ghs, notes);`
    : `-- No menu items were extracted. The planner can still choose this venue for
-- an activity stop, but it cannot build a food order from it.
insert into public.venues (
${venueColumns}
) values (
${venueValues}
);`;

  return `-- aduro — add venue: ${venue.name}
-- Generated by the admin ingest tool on ${generatedAt}.
--
-- Review before running. Prices came from a menu the model read; anything it
-- could not read was left out rather than guessed. Add image_url afterwards by
-- editing the venue at /admin/venues.
--
-- Any phone number goes to phone_pending, not phone. It stays unusable until
-- approved at /admin/phones — the reservation flow dials this number under
-- our own name, so it never goes live on an import alone.
--
-- Run in the Supabase SQL editor. Wrapped in a transaction, and the area is
-- created if this is the first venue in that neighbourhood.

begin;

-- Create the neighbourhood if this is the first venue in it.
insert into public.areas (name, city)
select ${lit(venue.areaName)}, 'Accra'
where not exists (select 1 from public.areas where name = ${lit(venue.areaName)});

${insertBlock}

commit;
`;
}

/** Filename an admin can drop straight into supabase/migrations/. */
export function migrationFilename(venueName: string): string {
  const slug = venueName
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "_")
    .replace(/^_+|_+$/g, "")
    .slice(0, 40);
  const stamp = new Date().toISOString().slice(0, 10).replace(/-/g, "");
  return `${stamp}_add_venue_${slug || "venue"}.sql`;
}
