-- A conversation is a sequence, and created_at was never able to say so.
--
-- persist() writes a whole exchange in one insert: the user's turn, the
-- assistant turn holding tool_use blocks, and the user turn holding the
-- matching tool_result blocks. created_at defaults to now(), and now() is the
-- transaction timestamp, so every row in that insert carries the same value to
-- the microsecond.
--
-- loadHistory then ordered by created_at alone. Ties in an ORDER BY have no
-- defined order in Postgres -- the planner returns them however the scan
-- happened to produce them, which is free to change with the query plan, the
-- table size or a vacuum. So the replay came back shuffled.
--
-- ── what that looked like ───────────────────────────────────────────────
-- One live conversation replayed as A U U A U A ... : it opened on an
-- assistant turn, and tool_result blocks arrived ahead of the tool_use blocks
-- they answer. Both are rejected outright -- the first message must be a user
-- turn, and a tool_result must follow its tool_use -- so the provider returned
-- 400 and the app said something about the conversation confusing it. Another
-- conversation with the same six tied timestamps came back in insertion order
-- and worked. Same bug, different luck, which is why it looked intermittent.
--
-- The fix is a column that actually increments. An identity column draws from
-- a sequence per row, so rows inserted together get increasing values in the
-- order they were passed, which is the order the exchange happened in.
--
-- Existing rows are filled in physical order, which for these two tables is
-- insertion order. That is not guaranteed in general, so the replay path also
-- learned to drop orphaned tool_use and tool_result blocks rather than send a
-- request it knows will be refused. Ordering is the fix; that is the seatbelt.
alter table public.messages
  add column if not exists seq bigint generated by default as identity;

-- created_at stays: it is what the transcript is stamped with and what any
-- cost reporting groups by. It is simply not an ordering.
comment on column public.messages.seq is
  'Replay order within a conversation. created_at cannot do this: a whole exchange is written in one insert and shares a single now(), and tied sort keys have no defined order, which returned turns shuffled and had the provider reject the request.';

create index if not exists messages_conversation_seq_idx
  on public.messages (conversation_id, seq);
