/**
 * The mascots for the home screen widget, as data URIs.
 *
 *   npm run widget:mascots
 *
 * The widget runs in its own process and cannot read the app's bundled
 * images, but Expo UI's Image loads `uiImage` with Data(contentsOf:), which
 * reads a data: URI as readily as a file. So each occasion's standing frame
 * travels inside the timeline the app hands the widget, and no file has to be
 * copied anywhere. About 2 KB each. Rerun after changing the art.
 */
import fs from "fs";
import path from "path";

const dir = path.join("mobile", "assets", "mascots");
const out = path.join("mobile", "src", "widgets", "mascots.ts");

// Standing frames only: the blink and bounce frames are for the app's animation.
const files = fs
  .readdirSync(dir)
  .filter((f) => f.endsWith(".png") && !/_(blink|bounce)\.png$/.test(f) && !f.startsWith("scene"))
  .sort();

const lines = files.map((f) => {
  const occasion = f.replace(/\.png$/, "");
  const b64 = fs.readFileSync(path.join(dir, f)).toString("base64");
  return `  ${occasion}: "data:image/png;base64,${b64}",`;
});

fs.writeFileSync(
  out,
  `// Generated by scripts/widget-mascots.ts from mobile/assets/mascots. Do not edit by hand.\n` +
    `// Each occasion's standing frame, for the home screen widget (see that script for why).\n\n` +
    `export const WIDGET_MASCOTS: Record<string, string> = {\n${lines.join("\n")}\n};\n`
);
console.log(`wrote ${out}: ${files.length} mascots, ${(fs.statSync(out).size / 1024).toFixed(1)} KB`);
