import type { SymbolViewProps } from "expo-symbols";

type AndroidSymbol = NonNullable<Extract<SymbolViewProps["name"], object>["android"]>;

/**
 * The Material Symbol Android draws for each SF Symbol the app uses. The app
 * names its icons in SF Symbols; this is the one place that says what they
 * look like on Android. A name missing here draws `FALLBACK`, so a new icon
 * never leaves a hole, but add it here when you use it.
 */
export const MATERIAL: Record<string, AndroidSymbol> = {
  "app.badge": "app_badging",
  "arrow.clockwise": "refresh",
  "arrow.right": "arrow_forward",
  "arrow.triangle.2.circlepath": "sync",
  "arrow.triangle.turn.up.right.diamond": "directions",
  "arrow.up": "arrow_upward",
  "arrow.up.right": "arrow_outward",
  bag: "shopping_bag",
  banknote: "payments",
  "birthday.cake": "cake",
  "birthday.cake.fill": "cake",
  bookmark: "bookmark",
  "bookmark.fill": "bookmark",
  "bubble.left.and.bubble.right": "forum",
  "bubble.left.and.bubble.right.fill": "forum",
  "bubble.left.and.text.bubble.right.fill": "forum",
  "building.2": "apartment",
  calendar: "calendar_month",
  "calendar.badge.plus": "calendar_add_on",
  "camera.fill": "photo_camera",
  "car.fill": "directions_car",
  checkmark: "check",
  "checkmark.circle": "check_circle",
  "checkmark.circle.fill": "check_circle",
  "chevron.down": "keyboard_arrow_down",
  "chevron.left": "chevron_left",
  "chevron.left.circle.fill": "arrow_circle_left",
  "chevron.right": "chevron_right",
  "chevron.up": "keyboard_arrow_up",
  "chevron.up.circle": "expand_circle_up",
  clock: "schedule",
  creditcard: "credit_card",
  "dice.fill": "casino",
  "doc.text": "description",
  "ellipsis.circle": "more_horiz",
  envelope: "mail",
  "envelope.fill": "mail",
  "envelope.badge.fill": "mark_email_unread",
  "exclamationmark.bubble": "feedback",
  "exclamationmark.circle.fill": "error",
  "exclamationmark.triangle": "warning",
  "exclamationmark.triangle.fill": "warning",
  "figure.and.child.holdinghands": "family_restroom",
  "figure.bowling": "sports",
  "figure.walk": "directions_walk",
  "fork.knife": "restaurant",
  gamecontroller: "sports_esports",
  "gift.fill": "redeem",
  "graduationcap.fill": "school",
  "hand.raised": "back_hand",
  "hand.thumbsup": "thumb_up",
  "hand.thumbsup.fill": "thumb_up",
  heart: "favorite",
  "heart.fill": "favorite",
  house: "home",
  "house.fill": "home",
  "info.circle": "info",
  iphone: "smartphone",
  "iphone.radiowaves.left.and.right": "vibration",
  leaf: "eco",
  "leaf.fill": "eco",
  link: "link",
  "location.fill": "near_me",
  "lock.iphone": "mobile_lock_portrait",
  magnifyingglass: "search",
  map: "map",
  "map.fill": "map",
  mappin: "location_on",
  "mappin.and.ellipse": "pin_drop",
  "menucard.fill": "menu_book",
  message: "chat_bubble",
  "message.fill": "chat_bubble",
  "mic.fill": "mic",
  "minus.circle": "do_not_disturb_on",
  "minus.circle.fill": "do_not_disturb_on",
  moon: "dark_mode",
  "moon.stars.fill": "bedtime",
  "music.note": "music_note",
  "party.popper.fill": "celebration",
  pencil: "edit",
  percent: "percent",
  person: "person",
  "person.fill": "person",
  "person.2.fill": "group",
  "person.3": "groups",
  "person.3.fill": "groups",
  "person.crop.circle": "account_circle",
  "person.crop.circle.badge.questionmark": "person_search",
  "person.crop.circle.badge.xmark": "person_remove",
  phone: "call",
  "phone.fill": "call",
  "phone.down": "call_end",
  "play.fill": "play_arrow",
  plus: "add",
  "plus.circle": "add_circle",
  "plus.circle.fill": "add_circle",
  "rectangle.portrait.and.arrow.right": "logout",
  sparkles: "auto_awesome",
  "square.and.arrow.up": "share",
  star: "star",
  "star.fill": "star",
  "sun.max": "light_mode",
  ticket: "confirmation_number",
  timer: "timer",
  trash: "delete",
  tshirt: "apparel",
  "wand.and.stars": "auto_fix_high",
  waveform: "graphic_eq",
  wineglass: "wine_bar",
  xmark: "close",
  "xmark.circle": "cancel",
  "xmark.circle.fill": "cancel",
};

export const FALLBACK: AndroidSymbol = "circle";
